### ISSUE TITLE
ImportFromCSV action is missing

### ISSUE THREAD

**Issue by swacsa** [SenseNet/sn-webpages#22]
Hi! 
I tried to use the ImportFromCSV action under the Root/IMS/ section to import users, but it is not listed in the ActionList. 
Is this function still exists in SN7?

**Comment by tusmester** [comment]
The action is there, it is just not in the appropriate scenario. As a workaround, you can add the **ExploreActions** scenario on the action's edit page:

> /Root/(apps)/Folder/ImportFromCsv

After that the action should appear in Content Explorer in the Actions menu on the toolbar.

We should try to come up with a more modern solution, because this action builds on the old WebForms UI and it is there only to aid old projects. Maybe an **snadmin step** that uses the same api in the background.

**Comment by swacsa** [comment]
I've found this action, so 
1. I went back to the IMS/(apps) folder
2. I've created a folder type content named "Folder"
3. Copy the ImportFromCsv action to here
4. Go back to the IMS/Portal domain
5. I can use now this action, I succesfully imported an user from csv!!! 👍 

Thanks!
